# Generated by Django 2.0.7 on 2018-08-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0003_auto_20180731_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='weights_path',
            field=models.CharField(blank='True', max_length=200),
        ),
    ]
