# Generated by Django 2.1 on 2019-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=200)),
                ('collection_link', models.URLField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('weights_path', models.CharField(blank='True', max_length=200)),
                ('kdtree_path', models.CharField(blank='True', max_length=200)),
                ('page2word_path', models.CharField(blank='True', max_length=200)),
                ('wrd_pos_fpath', models.CharField(blank='True', max_length=200)),
                ('words_path', models.CharField(blank='True', max_length=200)),
                ('demo_path', models.CharField(blank='True', max_length=200)),
            ],
        ),
    ]
