# Generated by Django 2.1 on 2019-02-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190218_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='kdtree_path',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='page2word_path',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='weights_path',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='wrd_pos_fpath',
        ),
        migrations.AddField(
            model_name='collection',
            name='language',
            field=models.CharField(blank='True', max_length=200),
        ),
    ]
