# Generated by Django 2.0 on 2021-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190221_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='api_cname',
            field=models.CharField(blank='True', max_length=200),
        ),
    ]
